### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Sanjudec4** [abhimanyusinghgaur/LeaveManagementSystem#1]
displays fatal error 

`Fatal error: Can't use method return value in write context in E:\xampp\htdocs\lms1\user\classDatabaseLeaveRequest.php on line 20`

**Comment by abhimanyusinghgaur** [comment]
Appologies for late reply!

You need to have **PHP 5.5+** as mentioned in [README](../blob/master/README.md).
See [this StackOverflow answer](http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context/4328049#4328049) for further explanation.

@Sanjudec4  I think you got what you wanted from [here](https://github.com/olivertsesk/Leave-Management-System). :grin: :stuck_out_tongue_winking_eye:
